#!/bin/bash

#------------------------------------------------------------------------------------------------------------
# Mount Aber Uni Storage Drives using sshfs
# Author: Sophie Short
# Date last modified: 2024.01.22
# Version: 0.1.2
#------------------------------------------------------------------------------------------------------------
version="0.1.2"
dateModified="2024.01.22"

istr=$1
istrcaps=${istr^^}
userstr=$2

dirstring=""


Help()
{
    echo "=================================================="
    echo "                       HELP                       "
    echo "=================================================="
    echo
    echo "Syntax: uniconnect [targetDrive] [username]"
    echo "        uniconnect [-c|h|V] [optArgs]"
    echo
    echo "Suggested [targetDrive] options:"
    echo "      \"impacs\"  : 'P'drive"
    echo "      \"aber\"    : 'M'drive"
    echo
    echo "options:"
    echo
    echo "c     Cleanup Directories."
    echo "      [optArgs] mount directory"
    echo
    echo "h     Print this Help text and exit."
    echo
    echo "V     Print software version and exit."
    echo
}

Version()
{
    echo "uniconnect"
    echo
    echo "Version: " $version
    echo "Author: Sophie Short"
    echo "Last Modified: " $dateModified
    echo
}

Cleanup()
{
    if [ ! $dirstring = "" ]
    then
        if [ -d $HOME/${dirstring^^} ];
        then
            rm -r $HOME/${dirstring^^}
        fi
    fi
}

CheckMakeDir()
{
    if [ ! -d $HOME/$istrcaps ]; 
    then
        mkdir $HOME/$istrcaps
    fi
}

Connect()
{
    sshfs $userstr@shellsrv.dcs.aber.ac.uk:/$istr/$userstr/ $HOME/$istrcaps
}

while getopts "c:hV" option; do
   case $option in
    c)  #clean directories
        dirstring=${OPTARG}
        Cleanup
        exit;;
    h)  # display Help
        Help
        exit;;
    V)  # Version info
        Version
        exit;;
    \?) # Invalid option
        echo "Error: Invalid option"
        exit;;
   esac
done

if [ ! $istr = "" ] && [ ! $userstr = "" ];
then
    CheckMakeDir
    Connect
else
    echo "[targetDrive] and [username] are required."
fi