#!/bin/bash

#------------------------------------------------------------------------------------------------------------
# Mount Aber Uni Storage Drives using sshfs
# Author: Sophie Short
# Date last modified: 2024.01.19
# Version: 0.1.0
#------------------------------------------------------------------------------------------------------------
# MUST have directories ~/IMPACS & ~/ABER to mount to


echo "Enter drive to connect to:"
echo "Available drives:"
echo "- impacs : P-drive"
echo "- aber   : M-drive"

read istr
istrcaps=${istr^^}

echo "Enter user:"
read userstr
sshfs $userstr@shellsrv.dcs.aber.ac.uk:/$istr/$userstr/ ~/$istrcaps
